apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: opl1h4ikh-go
  janus-idp.io/tekton: opl1h4ikh-go
  backstage.io/kubernetes-id: opl1h4ikh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: opl1h4ikh-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
