apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: opl1h4ikh-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opl1h4ikh-go 
  name: opl1h4ikh-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: opl1h4ikh-go 
